sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2"
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -e -B
script:
- mvn install test -e -B
